FROM php:7.0.9-fpm
RUN docker-php-ext-install opcache && \
echo opcache.enable=1 >> /usr/local/etc/php/php.ini
RUN apt-get update && \
pecl install xdebug && \
docker-php-ext-enable xdebug && \
rm -rf /var/lib/apt/lists/*
COPY xdebug.ini xdebug.ini
RUN cat xdebug.ini >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
RUN echo expose_php=0 >> /usr/local/etc/php/conf.d/extra.ini
